// SPDX-License-Identifier: MIT
pragma solidity ^0.8.22;

import {AccessControl} from "@openzeppelin/contracts/access/AccessControl.sol";

interface IGroth16Verifier {
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[3] calldata input
    ) external view returns (bool);
}

/**
 * @title RewardClaimVerifier
 * @notice Wrapper around a Groth16 verifier contract with nullifier protection.
 * @dev The actual curve operations live in an external verifier contract generated by snarkjs.
 *      This wrapper enforces access control, tracks nullifier usage, and prevents bypassing proofs.
 * @dev SECURITY FIX: Only authorized distributors can consume nullifiers to prevent grief attacks
 */
contract RewardClaimVerifier is AccessControl {
    bytes32 public constant ADMIN_ROLE = DEFAULT_ADMIN_ROLE;
    bytes32 public constant DISTRIBUTOR_ROLE = keccak256("DISTRIBUTOR_ROLE");

    struct Proof {
        uint256[2] a;
        uint256[2][2] b;
        uint256[2] c;
    }

    IGroth16Verifier public verifierContract;

    mapping(bytes32 => bool) public usedNullifiers;

    event ProofVerified(address indexed user, bytes32 indexed nullifier, uint256 claimAmount);
    event NullifierUsed(bytes32 indexed nullifier);
    event VerifierContractUpdated(address indexed newVerifier);

    constructor() {
        _grantRole(ADMIN_ROLE, msg.sender);
    }

    /**
     * @notice Configure the underlying Groth16 verifier contract.
     * @param newVerifier Address of the verifier contract generated from the Circom circuit.
     */
    function setVerifierContract(address newVerifier) external onlyRole(ADMIN_ROLE) {
        require(newVerifier != address(0), "RewardClaimVerifier: verifier zero");
        verifierContract = IGroth16Verifier(newVerifier);
        emit VerifierContractUpdated(newVerifier);
    }

    /**
     * @notice Verify a ZK proof against the configured verifier without consuming the nullifier.
     * @dev Reverts if the verifier contract is not configured or if the nullifier is already used.
     */
    function verifyProof(
        Proof memory proof,
        uint256[3] memory input
    ) public view returns (bool) {
        address verifierAddr = address(verifierContract);
        require(verifierAddr != address(0), "RewardClaimVerifier: verifier not set");

        bytes32 nullifier = bytes32(input[1]);
        require(!usedNullifiers[nullifier], "RewardClaimVerifier: nullifier already used");

        bool ok = verifierContract.verifyProof(proof.a, proof.b, proof.c, input);
        require(ok, "RewardClaimVerifier: proof verification failed");
        return true;
    }

    /**
     * @notice Verify a proof and mark the nullifier as consumed.
     * @dev Emits events to support downstream indexing.
     * @dev SECURITY FIX: Only authorized distributors can consume nullifiers to prevent grief attacks
     */
    function verifyAndUseProof(
        Proof memory proof,
        uint256[3] memory input
    ) external onlyRole(DISTRIBUTOR_ROLE) returns (bool) {
        verifyProof(proof, input);

        bytes32 nullifier = bytes32(input[1]);
        usedNullifiers[nullifier] = true;

        emit ProofVerified(msg.sender, nullifier, input[2]);
        emit NullifierUsed(nullifier);
        return true;
    }
    
    /**
     * @notice Grant distributor role to a contract
     * @param distributor Address of the distributor contract (e.g., ZKMerkleDistributor)
     */
    function grantDistributorRole(address distributor) external onlyRole(ADMIN_ROLE) {
        require(distributor != address(0), "RewardClaimVerifier: zero address");
        _grantRole(DISTRIBUTOR_ROLE, distributor);
    }
    
    /**
     * @notice Revoke distributor role from a contract
     * @param distributor Address to revoke role from
     */
    function revokeDistributorRole(address distributor) external onlyRole(ADMIN_ROLE) {
        _revokeRole(DISTRIBUTOR_ROLE, distributor);
    }

    /**
     * @notice Check if a nullifier has already been consumed.
     */
    function isNullifierUsed(bytes32 nullifier) external view returns (bool) {
        return usedNullifiers[nullifier];
    }
}
